pub mod common;
pub mod logs;
pub mod metrics;

pub mod pb {
    // Generated by tonic-prost-build: not held to the workspace lint policy.
    #![allow(clippy::all, clippy::pedantic)]

    pub mod common {
        pub mod v1 {
            tonic::include_proto!("opentelemetry.proto.common.v1");
        }
    }

    pub mod resource {
        pub mod v1 {
            tonic::include_proto!("opentelemetry.proto.resource.v1");
        }
    }

    pub mod logs {
        pub mod v1 {
            tonic::include_proto!("opentelemetry.proto.logs.v1");
        }
    }

    pub mod metrics {
        pub mod v1 {
            tonic::include_proto!("opentelemetry.proto.metrics.v1");
        }
    }

    pub mod collector {
        pub mod logs {
            pub mod v1 {
                tonic::include_proto!("opentelemetry.proto.collector.logs.v1");
            }
        }

        pub mod metrics {
            pub mod v1 {
                tonic::include_proto!("opentelemetry.proto.collector.metrics.v1");
            }
        }
    }
}

pub(crate) use common::{
    attribute_value, attributes, check_any_value, check_attributes, check_plain_string,
    convert_resource, parse_span_id, parse_trace_id,
};

// Imported here so signal mapping modules can refer to them as
// `super::AnyValue`, `super::AnyValueKind`.
use pb::common::v1::{AnyValue, any_value::Value as AnyValueKind};
